# 默认激活dev环境
spring:
  profiles:
    active: ${profiles.active}

---
###开发环境配置如下###
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root@123
    url: jdbc:mysql://localhost:3306/febs_base?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10s
    database: 0
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 10
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 2
        max-wait: 10s
  cache:
    type: redis

mybatis-plus:
  type-aliases-package: com.hujianguo.domain
  typeEnumsPackage: com.hujianguo.enums
  global-config:
    db-config:
      # 主键策略
      id-type: auto
      # 表前缀
      table-prefix: t_
      # 逻辑已删除值(默认为 0)
      logic-delete-value: 0
      # 逻辑未删除值(默认为 1)
      logic-not-delete-value: 1
    banner: false
  mapper-locations: classpath:mybatis/mapper/*.xml

---
###开发环境配置如下###
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root@123
    url: jdbc:mysql://47.96.103.162:3306/febs_base?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10s
    database: 0
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 10
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 2
        max-wait: 10s
  cache:
      type: redis

mybatis-plus:
  type-aliases-package: com.hujianguo.domain
  typeEnumsPackage: com.hujianguo.enums
  global-config:
    db-config:
      # 主键策略
      id-type: auto
      # 表前缀
      table-prefix: t_
      # 逻辑已删除值(默认为 0)
      logic-delete-value: 0
      # 逻辑未删除值(默认为 1)
      logic-not-delete-value: 1
    banner: false
  mapper-locations: classpath:mybatis/mapper/*.xml